version: '3.7' 

services:
  backend:
    image: 'backend:latest'
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    command: night

  frontend:
    image: 'frontend:latest'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: echo "Frontend"